### ISSUE TITLE
arguments[i].apply is not a function

### ISSUE THREAD

**Issue by micky2be** [novemberborn/babel-plugin-es6-promise#25]
Since I introduced your plugin I'm getting the following error when building my application.

```bash
TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/micky2be/Projects/node_modules/tapable/lib/Tapable.js:306:16)
    at webpack (/Users/micky2be/Projects/node_modules/webpack/lib/webpack.js:32:19)
    at processOptions (/Users/micky2be/Projects/node_modules/webpack/bin/webpack.js:305:14)
    at Object.<anonymous> (/Users/micky2be/Projects/node_modules/webpack/bin/webpack.js:363:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

webpack: 2.6.1
es6-promise: 4.1.0
babel-plugin-es6-promise: 1.1.1

**Comment by novemberborn** [comment]
There's probably a bunch of edge-cases this plugin doesn't consider, or your usage of `es6-promise` isn't supported by that library.

If you can find the root cause and open a PR there's a good chance it'll get merged, but otherwise I can't help you.

**Comment by marccerrato** [comment]
Same happened to me. You are adding `"plugins": ["es6-promise"]` to your **webpack** config, and you need to add it to your **babel** config.
